# Generated by Django 5.1 on 2024-09-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_recipe_recipeimage_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tym',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
