# Generated by Django 5.1 on 2024-09-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_recipe_tym_alter_recipe_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tym',
            field=models.IntegerField(default=0),
        ),
    ]
