# Generated by Django 5.1 on 2024-09-22 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tym',
            new_name='views',
        ),
    ]
