# Generated by Django 5.1 on 2024-09-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='classify',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
