# Generated by Django 5.1 on 2024-09-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_recipe_classify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='classify',
            field=models.CharField(choices=[('Mặn', 'Mặn'), ('Chay', 'Chay'), ('Kiên', 'Kiên'), ('Béo', 'Béo')], max_length=10),
        ),
    ]
